# Continuous integration handling for GoReleaser
name: ci-goreleaser

on:
  pull_request:
    paths:
      - .goreleaser.yml

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: go-version
        # Reference: https://github.com/actions/setup-go/issues/23
        run: echo "::set-output name=version::$(cat ./.go-version)"
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: check
